### ISSUE TITLE
Install Bootstrap

### ISSUE THREAD

**Issue by GosuSheep** [robber333/hs-drafter#8]
Bootstrap is a framework for formatting websites to be used nicely on mobile devices and desktops.

Installation instructions:

**(1) Add the gem to the Gemfile**
```
gem 'bootstrap-sass'
```
**(2) Rename app/assets/stylesheets/application.css to "application.css.scss"**

This allows us to use SASS in our CSS file.

**(3) Put the following into app/assets/stylesheets/application.css.scss:**
```
@import 'bootstrap';
@import 'bootstrap-sprockets';
```

**(4) Make our app/assets/javascripts/application.js look like this by adding bootstrap under turbolinks but above tree:**
```
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require bootstrap
//= require_tree . 
```

**(5) Add some bootstrap for fun by adding some text to card form**
(a) Edit the file /app/views/cards/show.html.erb
(b) Surround all the text there with this:
```
<div class="container">
... Stuff goes heres
</div>

We'll add a lot more later on.

**Comment by robber333** [comment]
You did this right? If so go ahead and close issue. Unless youre leaving it open as a reminder expand on this later, etc.
